Hub-01-Broadcast/Controllers/BroadcastController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hub_01_Broadcast.Controllers
{
    public class BroadcastController : Controller
    {
        // GET: Broadcast
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hub-01-Broadcast/Views/Broadcast/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="jumbotron text-center">
    <h1>ASP.NET SignalR</h1>
    <p>Broadcast usando Hubs</p>
</div>

<div class="container">
    <input type="text" class="form-control" id="msg" />
    <button class="btn btn-success" id="broadcast">Broadcast</button>
    <hr />

    <ul id="messages" class="list-group"></ul>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            var broadcaster = $.connection.broadcastHub;

            broadcaster.client.displayText = function (text) {
                $('#messages').append(`<li class="list-group-item">${text}</li>`);
            }

            $.connection.hub.start().done(function () {
                $('#broadcast').click(function () {
                    broadcaster.server.broadcastMessage($('#msg').val());
                    $('#msg').val('').focus();
                });
            });
        });
    </script>
    }

Hub-01-Broadcast/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Broadcast", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="signalr/hubs"></script>

    @RenderSection("scripts", false)
</body>
</html>